name: 'DORA lead time for changes'
description: 'A GitHub Action to roughly calculate DORA lead time for changes'
inputs:
  workflows: # required. string array of the name of the workflows to process
    description: 'the workflow name that is being scanned. Separate multiple workflows with commas'
    required: true
  owner-repo: # optional, defaults to current owner/repo
    description: 'the target org/repo or owner/repo to run the calculation on'
    required: true
    default: "${{ github.repository }}"
  default-branch:  # optional, defaults to main
    description: 'branch that is deploying to production'
    required: true
    default: 'main'
  number-of-days: # optional, defaults to 30
    description: number of days to scan
    required: true
    default: 30
  commit-counting-method: #optional, defaults to 'last'
    description: accepts two values, 'last' - to start timing from the last commit of a PR, and 'first' to start timing from the first commit of a PR
    required: true
    default: 'last'
  pat-token: # optional, defaults to an empty string ("")
    description: GitHub PAT Token
    default: ""
  actions-token: # optional, defaults to an empty string ("")
    description: GitHub Actions Token, commonly passed in as a variable (secrets.GITHUB_TOKEN)
    default: ""
  app-id:
    description: 'application id of the registered GitHub app'
    default: ""
  app-install-id:
    description: 'id of the installed instance of the GitHub app'
    default: ""
  app-private-key:
    description: 'private key which has been generated for the installed instance of the GitHub app'
    default: ""
runs:
  using: "composite"
  steps:
    - name: Run DORA lead time for changes
      shell: pwsh
      run: |
         $result = ${{ github.action_path }}/src/leadtimeforchanges.ps1 -ownerRepo "${{ inputs.owner-repo }}" -workflows "${{ inputs.workflows }}" -branch "${{ inputs.default-branch }}" -numberOfDays ${{ inputs.number-of-days }} -commitCountingMethod ${{ inputs.commit-counting-method }} -patToken "${{ inputs.pat-token }}" -actionsToken "${{ inputs.actions-token }}" -appId "${{ inputs.app-id }}" -appInstallationId "${{ inputs.app-install-id }}" -appPrivateKey "${{ inputs.app-private-key }}"             
         #Write-Host "::set-output name=result::$result"
         Write-Output $result >> $env:GITHUB_STEP_SUMMARY